[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32 @ 7.0.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 3000000
upload_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D CORE_DEBUG_LEVEL=0
    -D EV_REAR_UART_MODE=1
    -D EV_BMS_CAN_ENABLED=1
